### ISSUE TITLE
Error on repo install

### ISSUE THREAD

**Issue by AleBonatti** [spatie/medialibrary-demo-laracon-us#1]
Hi,
I cloned the repo and fired a composer update command, but at the end of the process I get this error:

_Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In Demo.php line 18:

  copy(/home/methlab/www/MethLab/medialibrary-demo-laracon-us/storage/demo/no
  va-talk-notes.pdf): failed to open stream: No such file or directory

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1_

Am I doing something wrong?

**Comment by freekmurze** [comment]
I pushed a fix. Please try cloning the repo again.

**Comment by AleBonatti** [comment]
It works. Thank you.
